import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <strong>Reproduction:</strong>
        <ol>
          <li>
            Navigate to a <Link href="/foo">non-existing page</Link>
          </li>
          <li>See how the custom 404 is not displayed</li>
          <li>
            Rename{" "}
            <pre style={{ display: "inline-block", background: "#DDD" }}>
              /src/app
            </pre>{" "}
            to{" "}
            <pre style={{ display: "inline-block", background: "#DDD" }}>
              /src/somethingelse
            </pre>{" "}
            and restart the next dev server
          </li>
          <li>
            Navigate to a <Link href="/foo">non-existing page</Link>
          </li>
          <li>See how the custom 404 is displayed</li>
        </ol>
      </main>
    </>
  );
}
